### ISSUE TITLE
Gdal.SetConfigOption exception encountered for x64 

### ISSUE THREAD

**Issue by ylimemily** [gisinternals/buildsystem#160]
Hi,

I downloaded gdal 2.4.4 and gdal.native 2.4.4 through nuget.org in a C# project and I am encountering exceptions in Gdal.SetConfigOption calls in GdalConfiguration.cs. The exceptions only occurs if the nativePath variable is set to x64 , it works fine when set to x86.

I think this has been raised before in this [link ](https://github.com/OSGeo/gdal/issues/1616) but the latest version available in nuget is 2.4.4 and I'm still encountering the issue. So i'm not sure if this has been fixed or is there another version that I can grab from nuget? Thanks.

Below is the trace output:
--- End of inner exception stack trace ---
   at OSGeo.GDAL.GdalPINVOKE.SetConfigOption(String jarg1, String jarg2)
   at OSGeo.GDAL.Gdal.SetConfigOption(String pszKey, String pszValue)
   at TestGdal.GdalConfiguration..cctor() in D:\Visual Studio 2015\Projects\CheckGdal\TestGdal\TestGdal\GdalConfiguration.cs:line 96
error: Executing directory: D:\Visual Studio 2015\Projects\CheckGdal\TestGdal\TestGdal\bin\Debug
error: gdal directory: D:\Visual Studio 2015\Projects\CheckGdal\TestGdal\TestGdal\bin\Debug\gdal
error: native directory: D:\Visual Studio 2015\Projects\CheckGdal\TestGdal\TestGdal\bin\Debug\gdal\x64

**Comment by ylimemily** [comment]
More stack trace info:
Exception thrown: 'System.TypeInitializationException' in gdal_csharp.dll
error: System.TypeInitializationException: The type initializer for 'OSGeo.GDAL.GdalPINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_Gdal(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..ctor()
   at OSGeo.GDAL.GdalPINVOKE..cctor()
   --- End of inner exception stack trace ---

**Comment by Costigan** [comment]
I think I'm seeing the same or a closely-related issue with Gdal and Gdal.Native 3.7.1, also downloaded via nuget.

The inner exception thrown when calling Gdal.SetConfigOption("GDAL_DATA", gdalData) is Unable to load DLL 'gdal_wrap': The specified procedure could not be found. (Exception from HRESULT: 0x8007007F)

I've compiled for x64.  When I compile for Any CPU, this SetConfigOption succeeds, although it runs into problems later.
It does get far enough to print the drivers (Gdal.GetDriverCount() returns 202).

(I run into System.ApplicationException: missing [
   at OSGeo.OSR.SpatialReference..ctor(String wkt)
   ...
later, which didn't occur in the older version I was using.

**Comment by syboldwerff** [comment]
3.7.2 has the same issue, any workaround or fix available.

**Comment by jonasnordlund** [comment]
I've been hit by this, precisely as in https://github.com/gisinternals/buildsystem/issues/160#issuecomment-1701869461 in 3.9.1.

Strangely enough, I'm using 3.9.1 in another project with the same files in the gdal subdirectory and *_csharp.dll's in the application directory, and it seems to be working there. I have a hunch it's somehow about auxiliary files that get involved here.

I used Dependency Walker on gdal_wrap along with the disassembled .NET code and this entry point was found in gdal_wrap.dll so I'm 99% sure it's talking of some other entry point / version conflict.

    [DllImport("gdal_wrap", EntryPoint = "CSharp_OSGeofGDAL_SetConfigOption___")]
    public static extern void SetConfigOption(string jarg1, string jarg2);
