### ISSUE TITLE
Could not load file or assembly 'ScintillaNet, Version=2.2.4148.33544

### ISSUE THREAD

**Issue by yvach** [gisinternals/buildsystem#179]
Hello,

Thanks for the amazing work you do. 

After installing MapManager x64, i have an error when trying to use the tool "Style Library..." 

I got :

![image](https://user-images.githubusercontent.com/89088230/129746812-32205c1f-97a0-404a-881b-b7e44f8391ea.png)

_`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileLoadException: Could not load file or assembly 'ScintillaNet, Version=2.2.4148.33544, Culture=neutral, PublicKeyToken=948d6c9751444115' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'ScintillaNet, Version=2.2.4148.33544, Culture=neutral, PublicKeyToken=948d6c9751444115'
   at DMS.MapLibrary.StyleLibraryForm.InitializeComponent()
   at DMS.MapLibrary.StyleLibraryForm..ctor(MapObjectHolder target)
   at DMS.MapManager.MainForm.styleLibraryToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`_

**Comment by yvach** [comment]
After reinstalling with the daily built it works fine.
