### ISSUE TITLE
Cannot run Python scripts with latest in Python 3.9 x64

### ISSUE THREAD

**Issue by TroySchmidt** [gisinternals/buildsystem#180]
```
C:\Program Files\GDAL>python gdal2xyz.py
Traceback (most recent call last):
  File "C:\Program Files\GDAL\gdal2xyz.py", line 5, in <module>
    from osgeo_utils.gdal2xyz import *  # noqa
  File "C:\Python39\lib\site-packages\osgeo_utils\gdal2xyz.py", line 39, in <module>
    from osgeo import gdal
  File "C:\Python39\lib\site-packages\osgeo\gdal.py", line 1920, in <module>
    import ogr
ModuleNotFoundError: No module named 'ogr'
```
Even after setting up the `PATH` environment variable and the `USE_PATH_FOR_GDAL_PYTHON` variable still doesn't work.

**Comment by TroySchmidt** [comment]
I did finally get GDAL Python bindings working by using a wheel I downloaded.  When I go to similar lines in it they are doing the imports differently.  
```
import osgeo.ogr
import osgeo.osr
```
Where these bindings are just doing the old fashion
```
import ogr
import osr
```

**Comment by szekerest** [comment]
py 3.9 support is already in place
