### ISSUE TITLE
Current release from MapManager is not running on Windows

### ISSUE THREAD

**Issue by szekerest** [gisinternals/buildsystem#197]
the current MapManager (MapManager (x64) (GDAL 3.5.0, MapServer 7.6.4)) is not running, in the event log is see:

 

Application: MapManager.exe

Framework Version: v4.0.30319

Description: The process was terminated due to an unhandled exception.

Exception Info: System.DllNotFoundException

   at OSGeo.MapServer.mapscriptPINVOKE+SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_mapscript(ExceptionDelegate, ExceptionDelegate, ExceptionDelegate, ExceptionDelegate, ExceptionDelegate, ExceptionDelegate, ExceptionDelegate, ExceptionDelegate, ExceptionDelegate, ExceptionDelegate, ExceptionDelegate)

   at OSGeo.MapServer.mapscriptPINVOKE+SWIGExceptionHelper..cctor()

 

Exception Info: System.TypeInitializationException

   at OSGeo.MapServer.mapscriptPINVOKE+SWIGExceptionHelper..ctor()

   at OSGeo.MapServer.mapscriptPINVOKE..cctor()

 

Exception Info: System.TypeInitializationException

   at OSGeo.MapServer.mapscriptPINVOKE.MAX_ERROR_LEN_get()

   at OSGeo.MapServer.mapscript..cctor()

 

Exception Info: System.TypeInitializationException

   at OSGeo.MapServer.mapscript.msGetVersion()

   at DMS.MapLibrary.MapUtils.SetPROJ_LIB(System.String)

   at DMS.MapManager.MainForm..ctor()

   at DMS.MapManager.Program.Main(System.String[])

 

 

I have tried the 32/64 bit version on Windows 10/11 (msi file).

**Comment by szekerest** [comment]
fixed
