### ISSUE TITLE
ImportError: No module named _gdal_array

### ISSUE THREAD

**Issue by TomGeoDK** [gisinternals/buildsystem#98]
Using the Python bindings for GDAL 2.1.0 in Python 2.7.12 (64) shows the same behaviour as described in issue #70 and #58.
I installed a fresh Python 2.7.12 (64) in Windows, installed Numpy via pip in version 1.11.2, then installed _gdal-201-1800-x64-core.msi_ and afterwards _GDAL-2.1.0.win-amd64-py2.7.msi_

The following code:

```
in_fobj = gdal.Open(in_file)
x_size = in_fobj.RasterXSize
y_size = in_fobj.RasterYSize
in_data = in_fobj.ReadAsArray(0, 0, x_size, y_size).astype(np.int8)
```

fails with:

```
Traceback (most recent call last):
  File "<pyshell#10>", line 1, in <module>
    in_data = in_fobj.ReadAsArray(0, 0, x_size, y_size).astype(np.int8)
  File "C:\Python27_seperate\lib\site-packages\osgeo\gdal.py", line 1825, in ReadAsArray
    import gdalnumeric
  File "C:\Python27_seperate\lib\site-packages\osgeo\gdalnumeric.py", line 1, in <module>
    from osgeo.gdal_array import *
  File "C:\Python27_seperate\lib\site-packages\osgeo\gdal_array.py", line 26, in <module>
    _gdal_array = swig_import_helper()
  File "C:\Python27_seperate\lib\site-packages\osgeo\gdal_array.py", line 18, in swig_import_helper
    import _gdal_array
ImportError: No module named _gdal_array
```

**Comment by szekerest** [comment]
This appears to be fixed in the recent SDK
